# Generated by Django 5.1.1 on 2024-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_userprofile_is_dark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selected_theme',
            field=models.CharField(default='light', max_length=25),
        ),
    ]
