# Generated by Django 5.1.1 on 2024-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('bootcamp', models.CharField(max_length=50)),
                ('portfolio_url', models.CharField(default='not-set', max_length=255)),
            ],
        ),
    ]
