# Generated by Django 5.1.1 on 2024-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstudent',
            name='bootcamp',
            field=models.CharField(default='not-set', max_length=50),
        ),
        migrations.AlterField(
            model_name='dbstudent',
            name='fullname',
            field=models.CharField(default='not-set', max_length=255),
        ),
    ]
